const misionesData = [
    {
        id: "M1",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "ALBA",
        titulo: "Aterrizaxe forzoso!",
        texto: "Calquera pode resbalar cando chove.",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/2PiCFMY6WDZ2ZTxg",
        dificil: 5, medio: 20, facil: 50,
        tiempo: "1 min 20 seg",
        regalo: "Pídello a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M2",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "HARIS",
        titulo: "Auga cae!",
        texto: "Estivemos xuntos.",
        tipoMedia: "video",
        archivoMedia: "imaxes/M2.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/I712jxQda7TgsK2N",
        dificil: 20, medio: 500, facil: 1500,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M3",
        categoria: "UN VOLTIO",
        autor: "BORJA",
        titulo: "OFNI",
        texto: "Escoita con atención:",
        tipoMedia: "audio",
        archivoMedia: "imaxes/M3.ogg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/2uVLPHdFscSlzUwC",
        dificil: 100, medio: 500, facil: 1500,
        tiempo: "5 min 50 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M4",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "MELLA",
        titulo: "Pasado por auga",
        texto: "Veña, poñamos a proba a tua memoria! Onde fixemos esta fotiño?",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M4.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/4uWui72TORmNMedo",
        dificil: 50, medio: 200, facil: 500,
        tiempo: "3 mins 50 seg",
        requiereFecha: true,
        fechaCorrecta: "15 de agosto",
        regalo: "<br><img src='imaxes/R4.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "Porque, que mellor regalo para facerche, que recordar unha das primeiras fotos que temos xuntos? Unha das miñas favs, porque solo con mirarnos, e ver o felices que éramos xuntos, se pode imaxinar unha pequena pequena parte do grande e valiosa que é a nosa amizade ❤️❤️❤️❤️"
    },
    {
        id: "M5",
        categoria: "UN VOLTIO",
        autor: "MARCOS",
        titulo: "4 A.M.",
        texto: "hai que lavala pirola",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/GHpQRsKLECI3x1HI",
        dificil: 50, medio: 200, facil: 500,
        tiempo: "2 mins 30 seg",
        regalo: "<br><img src='imaxes/R5.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "<br><br><b>Mensaxe Extra de Marcos:</b><br><audio controls style='width:100%'><source src='imaxes/M5.ogg'></audio>"
    },
    {
        id: "M6",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "CLARA",
        titulo: "Calor abrasador polo sol e polo alcol",
        texto: "Oro parece y no fue barato. En esta playa al agua caímos los cuatro. Si recuerdas bien aquella actividad hinchable, ¡busca en el mapa el lugar deseable!",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/208atDxOH5ehkRXV",
        dificil: 100, medio: 1000, facil: 2500,
        tiempo: "7 mins",
        regalo: "Pregúnatlle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M7",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "GERMÁN",
        titulo: "El emperador",
        texto: "Bota un ollo á imaxe...",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M7.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/WHlvlCSpSfzCHsFm",
        dificil: 100, medio: 500, facil: 1500,
        tiempo: "7 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M8",
        categoria: "UN VOLTIO",
        autor: "LAURA",
        titulo: "Felicitación milagreira",
        texto: "Tras un ano sen emitir máis ca sons de fax averiado, Laura recuperou milagrosamente a voz nun momento crucial: a felicitación dun cumpleanos. Este desafío de cumpleanos vai para o rei do coñecemento festivo… en que lugar se produciu esa felicitación milagreira?",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/sEHGFyLlpUhvzIMa",
        dificil: 20, medio: 100, facil: 500,
        tiempo: "2 mins",
        requiereFecha: true,
        fechaCorrecta: "9 de abril",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M9",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "ABEL",
        titulo: "¿?",
        texto: "Outra foto?",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/lNKWzZqZQEZFOeQ7",
        dificil: 20, medio: 100, facil: 500,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "<br><img src='imaxes/M9.jpeg' style='max-width:100%; border-radius:8px; margin-top:10px;'>"
    },
    {
        id: "M10",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "JULI",
        titulo: "Sinistro",
        texto: "A pregunta seria.. en que concello se produciu o sinistro?",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M10.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/Y0mcGUZc3PLwx0wu",
        dificil: 100, medio: 1000, facil: 2500,
        tiempo: "9 mins",
        regalo: "Pregúntalle a Alba",
         // 🔄 ANTI-BLOQUEO: Botón de neón magenta para abrir o vídeo extra de Julián sen erros
        textoPostAcerto: "<br><br><a href='https://youtu.be/5EHQMZp2Rrg?si=HVpyJ3YPR9DNRpc0' target='_blank' class='btn' style='border-color:var(--neon-magenta); color:var(--neon-magenta); box-shadow:0 0 15px var(--neon-magenta); text-shadow:0 0 5px var(--neon-magenta); display:inline-block; margin-top:10px; padding: 15px 30px; text-decoration: none;font-size: 1.1rem;'>🎬 PREME AQUÍ PARA VER O VÍDEO EXTRA DE JULI 🎬</a>"
    },
    {
        id: "M11",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "IVÁN",
        titulo: "CHO-CHO-CHÓFER PARE EL TAXI",
        texto: "Bota un ollo ao vídeo! E por se non o escoitas ben, aquí tes a proba de audio:<br><audio controls style='width:100%; margin-top:10px;'><source src='imaxes/M11.2.mp4'></audio>",
        tipoMedia: "video",
        archivoMedia: "imaxes/M11.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/TxBE56lLhEemaoTl",
        dificil: 50, medio: 100, facil: 500,
        tiempo: "1 min 30 seg",
        // 🔄 ANTI-BLOQUEO: Botón de neón verde para ver a túa recompensa sen Error 153
        regalo: "<br><br><a href='https://youtu.be/eHJzUPBRnFM' target='_blank' class='btn' style='border-color:var(--neon-green); color:var(--neon-green); box-shadow:0 0 15px var(--neon-green); text-shadow:0 0 5px var(--neon-green); display:inline-block; margin-top:10px; padding: 15px 30px; text-decoration: none; font-size: 1.1rem;'>🎁 CLICA AQUÍ PARA VER O TEU AGASALLO EN YOUTUBE 🎁</a>",
        // 🔄 ANTI-BLOQUEO: Botón de neón magenta para abrir o vídeo extra de Iván sen erros
        textoPostAcerto: "<br><br><a href='https://youtu.be/qRp3-D3SMwI' target='_blank' class='btn' style='border-color:var(--neon-magenta); color:var(--neon-magenta); box-shadow:0 0 15px var(--neon-magenta); text-shadow:0 0 5px var(--neon-magenta); display:inline-block; margin-top:10px; padding: 15px 30px; text-decoration: none;font-size: 1.1rem;'>🎬 PREME AQUÍ PARA VER O VÍDEO EXTRA DE IVÁN 🎬</a>"
    },
    {
        id: "M12",
        categoria: "UN VOLTIO",
        autor: "DIANA",
        titulo: "🍻",
        texto: "¡A beber!",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/Um0q3jVN6wUaqud1",
        dificil: 50, medio: 500, facil: 1000,
        tiempo: "5 mins",
        regalo: "Pregúntallle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M13",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "PIKI",
        titulo: "Mítico",
        texto: "Non é onde rompiches a costilla, pero si que rompeu algo",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/k7GHVnLaCEoEMt6t",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "1 min 30 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M14",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "ÁXEL",
        titulo: "Yo sé lo que cobra la cajera del Froiz porque se lo pregunté",
        texto: "Dando una vuelta con unos amigos, me encontré con Alba y contigo. Fuimos a tomar algo a este sitio y se nos unió alguien más. Tras varias cervezas, como si del programa de Broncano se tratase, se acabó falando de diñeiro. Tamén de certas figuras que se venden baratas para a gran calidade que teñen. Fue una pena que ninguno de los allí presentes fose especialmente aficionado a ellas.",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M14.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/30rHzxcVVoppEZF4",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "1 min 50 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M15",
        categoria: "UN VOLTIO",
        autor: "SÁMER",
        titulo: "Ola Alba! Momento/Pregunta/Como sexa para Aless",
        texto: "Despois de tirar esta foto fumos repostar os depósitos das motos e máis os nosos. Acabamos nun sitio aleatorio que che pareceu ver pasando ca moto. Tremendos chuletóns nos metimos. Acordas onde foi?",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M15.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/hxMpsAetsiQtMj4i",
        dificil: 50, medio: 300, facil: 850,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M16",
        categoria: "UN VOLTIO",
        autor: "EVA",
        titulo: "Mamá",
        texto: "estoy estudiando",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M16.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/B4rynBM7Iwir6ER4",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "No me acuerda en qué discoteca fuera… en alguna del Arenal 🤣 <br><img src='imaxes/M16.2.jpeg' style='max-width:100%; border-radius:8px; margin-top:10px;'>"
    },
    {
        id: "M17",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "REBECA",
        titulo: "Ola de calor",
        texto: "O famoso libro que iniciou a saga de novelas protagonizadas por Nikki Heat",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/3KkshmJc6ua9VEbs",
        dificil: 100, medio: 800, facil: 2500,
        tiempo: "7 mins",
        regalo: "<br><img src='imaxes/R17.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "Os dous estivemos viciadisimos a Castle, serie que comentábamos cando cuadrábamos. Aless, por un amigo invisible, regaloume o libro de Ola de Calor."
    },
    {
        id: "M18",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "RICHI",
        titulo: "El dirá que é mentira",
        texto: "“Lugar en el que Richi te gano un partido de tenis” Él dirá que es mentira.",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/dDHVluyNzXly4oW4",
        dificil: 10, medio: 30, facil: 50,
        tiempo: "1 min 10 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M19",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "LAURECHA",
        titulo: "Un vermucito",
        texto: "Onde foi sacada esta foto",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M19.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/42DHm5nsHDqgTBNN",
        dificil: 30, medio: 50, facil: 100,
        tiempo: "2 min",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M20",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "DARÍO",
        titulo: "Unha Banda",
        texto: "Onde foi sacada a foto?",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M20.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/HHEbp21StSDcTJxH",
        dificil: 20, medio: 50, facil: 100,
        tiempo: "2 mins",
        requiereFecha: true,
        fechaCorrecta: "26 de xuño de 2025",
        regalo: "<br><img src='imaxes/R20.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: ""
    },
    {
        id: "M21",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "PABLO (Carballiño)",
        titulo: "Andar agachados",
        texto: "Non tiveron en conta a cabeza",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/4egoU2u3dZG0tuqZ",
        dificil: 30, medio: 70, facil: 150,
        tiempo: "2 min 30 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "Ese foi o zulo no que nos quedamos en Xinzo o ano pasado, que tiñanos que andar agachados porque o teito estaba á altura dos hombros 😂"
    },
    {
        id: "M22",
        categoria: "UN VOLTIO",
        autor: "ESTELA",
        titulo: "Ser Graña",
        texto: "¿Dónde puedes sentarte, levantarte un momento y descubrir al volver que tu sitio, tu conversación y probablemente hasta tu interlocutor han cambiado?",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/pRDzJdyNYLpXkD1p",
        dificil: 20, medio: 40, facil: 60,
        tiempo: "1 min 20 seg",
        regalo: "<br><img src='imaxes/R22.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: ""
    },
    {
        id: "M23",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "LUIS",
        titulo: "A frase",
        texto: "eu agora cun jonny cola aguanto ata o domingo",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/x5v0KCT200MqF6Eo",
        dificil: 50, medio: 200, facil: 1000,
        tiempo: "5 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M24",
        categoria: "UN VOLTIO",
        autor: "DAMIÁN",
        titulo: "Festas",
        texto: "Fue un día que un amigo nuestro decidió que tenía calor y se quitó la camisa en pleno noviembre",
        tipoMedia: "video",
        archivoMedia: "imaxes/M24.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/Iti9wCZymi21PUx3",
        dificil: 50, medio: 150, facil: 500,
        tiempo: "2 mins 30 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "La anécdota es en las fiestas de san Martiño en Moaña, cuando vienen por aquí. Pues si tienes que darle pistas, fue un día que un amigo nuestro decidió que tenía calor y se quitó la camisa en pleno noviembre, el bueno de Javi Trigo 🫣🤭. Fue hace un par de años."
    },
    {
        id: "M25",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "PABLO GODANZA",
        titulo: "Go danzar",
        texto: "Pregunta: Obviamente a miña pregunta é unha festa, pero dónde estabamos aquí?",
        tipoMedia: "imagen",
        archivoMedia: "imaxes/M25.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/2xfQYP2FDejvT7k3",
        dificil: 20, medio: 100, facil: 250,
        tiempo: "1 min 30 seg",
        requiereFecha: true,
        fechaCorrecta: "30 de maio de 2017",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M26",
        categoria: "UN VOLTIO",
        autor: "JAVI",
        titulo: "Antes de todo",
        texto: "Bota un ollo ao vídeo:",
        tipoMedia: "video",
        archivoMedia: "imaxes/M26.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/R5HvKyxs2AqqxW3p",
        dificil: 30, medio: 100, facil: 200,
        tiempo: "3 min",
        requiereFecha: true,
        fechaCorrecta: "9 de xullo de 2016",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "O que mais gracia me fixo foi este video de antes de conocelo. <br><img src='imaxes/M26.png' style='max-width:100%; border-radius:8px; margin-top:10px;'>"
    },
    {
        id: "M27",
        categoria: "UN VOLTIO",
        autor: "COMESAÑA",
        titulo: "Reciclaxe",
        texto: "Onde case vas ao contenedor nunha cea",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/JYt7QhrEOPqMKrMU",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "3 min",
        regalo: "<br><img src='imaxes/R27.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "Somos uns borrachos non sei de que te sorprende aHahahahah"
    }
];