const misionesData = [
    {
        id: "M1",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "ALBA",
        titulo: "Aterrizaxe forzoso!",
        texto: "Calquera pode resbalar cando chove.",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/2PiCFMY6WDZ2ZTxg",
        dificil: 5, medio: 20, facil: 50,
        tiempo: "1 min 20 seg",
        regalo: "Pídello a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M2",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "HARIS",
        titulo: "Auga cae!",
        texto: "Estivemos xuntos.",
        tipoMedia: "video",
        archivoMedia: "Imaxes/M2.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/I712jxQda7TgsK2N",
        dificil: 20, medio: 500, facil: 1500,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M3",
        categoria: "UN VOLTIO",
        autor: "BORJA",
        titulo: "OVNI",
        texto: "Escoita con atención:",
        tipoMedia: "audio",
        archivoMedia: "Imaxes/M3.ogg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/2uVLPHdFscSlzUwC",
        dificil: 100, medio: 500, facil: 1500,
        tiempo: "5 min 50 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M4",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "MELLA",
        titulo: "Pasado por auga",
        texto: "Veña, poñamos a proba a tua memoria! Onde fixemos esta fotiño?",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M4.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/4uWui72TORmNMedo",
        dificil: 50, medio: 200, facil: 500,
        tiempo: "3 mins 50 seg",
        requiereFecha: true,
        fechaCorrecta: "15 de agosto",
        regalo: "<br><img src='Imaxes/R4.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "Porque, que mellor regalo para facerche, que recordar unha das primeiras fotos que temos xuntos? Unha das miñas favs, porque solo con mirarnos, e ver o felices que éramos xuntos, se pode imaxinar unha pequena pequena parte do grande e valiosa que é a nosa amizade ❤️❤️❤️❤️"
    },
    {
        id: "M5",
        categoria: "UN VOLTIO",
        autor: "MARCOS",
        titulo: "4 A.M.",
        texto: "Xuntos, auga, en bolas.",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/GHpQRsKLECI3x1HI",
        dificil: 50, medio: 200, facil: 500,
        tiempo: "2 mins 30 seg",
        regalo: "<br><img src='Imaxes/R5.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "<br><br><b>Mensaxe Extra de Marcos:</b><br><audio controls style='width:100%'><source src='Imaxes/M5.ogg'></audio>"
    },
    {
        id: "M6",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "CLARA",
        titulo: "Calor abrasador polo sol e polo alcol",
        texto: "Oro parece y no fue barato. En esta playa al agua caímos los cuatro. Si recuerdas bien aquella actividad hinchable, ¡busca en el mapa el lugar deseable!",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/m6iIjvuNvT4bul0q",
        dificil: 100, medio: 1000, facil: 2500,
        tiempo: "7 mins",
        regalo: "Pregúnatlle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M7",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "GERMÁN",
        titulo: "El emperador",
        texto: "Bota un ollo á imaxe...",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M7.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/uqeHNBPJtMr4K8t7",
        dificil: 100, medio: 500, facil: 1500,
        tiempo: "7 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M8",
        categoria: "UN VOLTIO",
        autor: "LAURA",
        titulo: "Felicitación milagreira",
        texto: "Tras un ano sen emitir máis ca sons de fax averiado, Laura recuperou milagrosamente a voz nun momento crucial: a felicitación dun cumpleanos. Este desafío de cumpleanos vai para o rei do coñecemento festivo… en que lugar se produciu esa felicitación milagreira?",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/sEHGFyLlpUhvzIMa",
        dificil: 20, medio: 100, facil: 500,
        tiempo: "2 mins",
        requiereFecha: true,
        fechaCorrecta: "9 de abril",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M9",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "ABEL",
        titulo: "¿?",
        texto: "Outra foto?",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/kOCgRRxiNuQpPP1A",
        dificil: 20, medio: 100, facil: 500,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "<br><img src='Imaxes/M9.jpeg' style='max-width:100%; border-radius:8px; margin-top:10px;'>"
    },
    {
        id: "M10",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "JULI",
        titulo: "Sinistro",
        texto: "A pregunta seria.. en que concello se produciu o sinistro?",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M10.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/86TFCT8yDomS6xvU",
        dificil: 100, medio: 1000, facil: 2500,
        tiempo: "9 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "<br><iframe width='100%' height='250' src='https://www.youtube.com/embed/5EHQMZp2Rrg' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen style='border-radius:8px; margin-top:10px;'></iframe>"
    },
    {
        id: "M11",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "IVÁN",
        titulo: "CHO-CHO-CHÓFER PARE EL TAXI",
        texto: "Bota un ollo ao vídeo! E por se non o escoitas ben, aquí tes a proba de audio:<br><audio controls style='width:100%; margin-top:10px;'><source src='Imaxes/M11.2.mp3'></audio>",
        tipoMedia: "video",
        archivoMedia: "Imaxes/M11.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/oJlgj8xUnuzRdDmk",
        dificil: 50, medio: 100, facil: 500,
        tiempo: "1 min 30 seg",
        regalo: "<br><video controls style='max-width:100%; border-radius:8px;'><source src='Imaxes/R11.mp4'></video>",
        textoPostAcerto: "<br><iframe width='100%' height='250' src='https://www.youtube.com/embed/qRp3-D3SMwI' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen style='border-radius:8px; margin-top:10px;'></iframe>"
    },
    {
        id: "M12",
        categoria: "UN VOLTIO",
        autor: "DIANA",
        titulo: "🍻",
        texto: "¡A beber!",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/JbMr6CXsNJEioaEL",
        dificil: 50, medio: 500, facil: 1000,
        tiempo: "5 mins",
        regalo: "Pregúntallle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M13",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "PIKI",
        titulo: "Mítico",
        texto: "Non é onde rompiches a costilla, pero si que rompeu algo",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/axGqhJLnf2ziBODk",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "1 min 30 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M14",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "ÁXEL",
        titulo: "Yo sé lo que cobra la cajeta del Froiz porque se lo pregunté",
        texto: "Dando una vuelta con unos amigos, me encontré con Alba y contigo. Fuimos a tomar algo a este sitio y se nos unió alguien más. Tras varias cervezas, como si del programa de Broncano se tratase, se acabó hablando de dinero. También de ciertas figuras que se venden baratas para la gran calidad que tienen. Fue una pena que ninguno de los allí presentes fuese especialmente aficionado a ellas.",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M14.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/lo1xL8PUHaLExJtd",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "1 min 50 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M15",
        categoria: "UN VOLTIO",
        autor: "SÁMER",
        titulo: "Ola Alba! Momento/Pregunta/Como sexa para Aless",
        texto: "Despois de tirar esta foto fumos repostar os depósitos das motos e máis os nosos. Acabamos nun sitio aleatorio que che pareceu ver pasando ca moto. Tremendos chuletóns nos metimos. Acordas onde foi?",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M15.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/TlQS6wucjQjZh79X",
        dificil: 50, medio: 300, facil: 850,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M16",
        categoria: "UN VOLTIO",
        autor: "EVA",
        titulo: "Mamá",
        texto: "estoy estudiando",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M16.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/tf2PYjUGcTUbyl9K",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "3 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "No me acuerda en qué discoteca fuera… en alguna del Arenal 🤣 <br><img src='Imaxes/M16.2.jpeg' style='max-width:100%; border-radius:8px; margin-top:10px;'>"
    },
    {
        id: "M17",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "REBECA",
        titulo: "Ola de calor",
        texto: "O famoso libro que iniciou a saga de novelas protagonizadas por Nikki Heat",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/auDIHCCS45jSQ2HX",
        dificil: 100, medio: 800, facil: 2500,
        tiempo: "7 mins",
        regalo: "<br><img src='Imaxes/R17.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "Os dous estivemos viciadisimos a Castle, serie que comentábamos cando cuadrábamos. Aless, por un amigo invisible, regaloume o libro de Ola de Calor."
    },
    {
        id: "M18",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "RICHI",
        titulo: "El dirá que é mentira",
        texto: "“Lugar en el que Richi te gano un partido de tenis” Él dirá que es mentira.",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/iMw0Oqc6piIOpQUO",
        dificil: 10, medio: 30, facil: 50,
        tiempo: "1 min 10 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M19",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "LAURECHA",
        titulo: "Un vermucito",
        texto: "Onde foi sacada esta foto",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M19.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/aV0V60lgBff2CHCG",
        dificil: 30, medio: 50, facil: 100,
        tiempo: "2 min",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M20",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "DARÍO",
        titulo: "Unha Banda",
        texto: "Onde foi sacada a foto?",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M20.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/Hi9OenhMvnR4Gb9p",
        dificil: 20, medio: 50, facil: 100,
        tiempo: "2 mins",
        requiereFecha: true,
        fechaCorrecta: "26 de xuño de 2025",
        regalo: "<br><img src='Imaxes/R20.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: ""
    },
    {
        id: "M21",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "PABRO (Carballiño)",
        titulo: "Andar agachados",
        texto: "Non tiveron en conta a cabeza",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/khuQA399ctgvb5OS",
        dificil: 30, medio: 70, facil: 150,
        tiempo: "2 min 30 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "Ese foi o zulo no que nos quedamos en Xinzo o ano pasado, que tiñanos que andar agachados porque o teito estaba á altura dos hombros 😂"
    },
    {
        id: "M22",
        categoria: "UN VOLTIO",
        autor: "ESTELA",
        titulo: "Ser Graña",
        texto: "¿Dónde puedes sentarte, levantarte un momento y descubrir al volver que tu sitio, tu conversación y probablemente hasta tu interlocutor han cambiado?",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/vthw2y6BircuEuCD",
        dificil: 20, medio: 40, facil: 60,
        tiempo: "1 min 20 seg",
        regalo: "<br><img src='Imaxes/R22.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: ""
    },
    {
        id: "M23",
        categoria: "CAMIÑAR É FACER CAMIÑO",
        autor: "LUIS",
        titulo: "A frase",
        texto: "eu agora cun jonny cola aguanto ata o domingo",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/nCbw4Ma62hTtPmG0",
        dificil: 50, medio: 200, facil: 1000,
        tiempo: "5 mins",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M24",
        categoria: "UN VOLTIO",
        autor: "DAMIÁN",
        titulo: "Festas",
        texto: "Fue un día que un amigo nuestro decidió que tenía calor y se quitó la camisa en pleno noviembre",
        tipoMedia: "video",
        archivoMedia: "Imaxes/M24.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/xuTBzphcEyZT8CQh",
        dificil: 50, medio: 150, facil: 500,
        tiempo: "2 mins 30 seg",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: "La anécdota es en las fiestas de san Martiño en Moaña, cuando vienen por aquí. Pues si tienes que darle pistas, fue un día que un amigo nuestro decidió que tenía calor y se quitó la camisa en pleno noviembre, el bueno de Javi Trigo 🫣🤭. Fue hace un par de años."
    },
    {
        id: "M25",
        categoria: "ESCONDITE INGLÉS (sen mover as mans nin os pés)",
        autor: "PABLO GODANZA",
        titulo: "Go danzar",
        texto: "Pregunta: Obviamente a miña pregunta é unha festa, pero dónde estabamos aquí?",
        tipoMedia: "imagen",
        archivoMedia: "Imaxes/M25.jpeg",
        linkGeoguessr: "https://www.geoguessr.com/challenge/rNzhg4dfbVYYrTTt",
        dificil: 20, medio: 100, facil: 250,
        tiempo: "1 min 30 seg",
        requiereFecha: true,
        fechaCorrecta: "30 de maio de 2017",
        regalo: "Pregúntalle a Alba",
        textoPostAcerto: ""
    },
    {
        id: "M26",
        categoria: "UN VOLTIO",
        autor: "JAVI",
        titulo: "Antes de todo",
        texto: "Bota un ollo ao vídeo:",
        tipoMedia: "video",
        archivoMedia: "Imaxes/M26.mp4",
        linkGeoguessr: "https://www.geoguessr.com/challenge/ZkH8NSGLshwWxWoQ",
        dificil: 30, medio: 100, facil: 200,
        tiempo: "3 min",
        requiereFecha: true,
        fechaCorrecta: "9 de xullo de 2016",
        regalo: "<br><img src='Imaxes/R26.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "O que mais gracia me fixo foi este video de antes de conocelo. <br><img src='Imaxes/M26.png' style='max-width:100%; border-radius:8px; margin-top:10px;'>"
    },
    {
        id: "M27",
        categoria: "UN VOLTIO",
        autor: "COMESAÑA",
        titulo: "Reciclaxe",
        texto: "Onde case vas ao contenedor nunha cea",
        tipoMedia: "texto",
        archivoMedia: "",
        linkGeoguessr: "https://www.geoguessr.com/challenge/CUn4gjdOBxNTEJuL",
        dificil: 20, medio: 50, facil: 150,
        tiempo: "3 min",
        regalo: "<br><img src='Imaxes/R27.png' style='max-width:100%; border-radius:8px;'>",
        textoPostAcerto: "Somos uns borrachos non sei de que te sorprende aHahahahah"
    }
];
